package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/gianpaoloaranha/go-social-network/internal/adapters/in/graphql/generated"
	"github.com/gianpaoloaranha/go-social-network/internal/adapters/in/graphql/generated/model"
	"github.com/gianpaoloaranha/go-social-network/internal/app/ports/comment"
	"github.com/gianpaoloaranha/go-social-network/internal/app/ports/post"
	"github.com/gianpaoloaranha/go-social-network/internal/app/ports/user"
	"github.com/gianpaoloaranha/go-social-network/internal/infra/authentication"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	session, err := r.AuthUsecase.Login(email, password)
	if err != nil {
		return authPayloadError("login", err), nil
	}

	user, err := r.assembleUser(session.User)
	if err != nil {
		return authPayloadError("login", err), nil
	}

	return &model.AuthPayload{
		AccessToken:  session.AccessToken,
		RefreshToken: session.RefreshToken,
		User:         user,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	session, err := r.AuthUsecase.RefreshToken(refreshToken)
	if err != nil {
		return authPayloadError("refreshToken", err), nil
	}

	user, err := r.assembleUser(session.User)
	if err != nil {
		return authPayloadError("refreshToken", err), nil
	}

	return &model.AuthPayload{
		AccessToken:  session.AccessToken,
		RefreshToken: session.RefreshToken,
		User:         user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return r.AuthUsecase.Logout(), nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.UserPayload, error) {
	userInput := user.CreateUserInput{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}
	createdUser, err := r.UserUsecase.CreateUser(userInput)
	if err != nil {
		return userPayloadError("createUser", err), nil
	}

	user, err := r.assembleUser(*createdUser)
	if err != nil {
		return userPayloadError("createUser", err), nil
	}

	return &model.UserPayload{
		User: user,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.UserPayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return userPayloadError("updateUser", errUnauthorized()), nil
	}

	userInput := user.UpdateUserInput{
		ID:       userID,
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}
	updatedUser, err := r.UserUsecase.UpdateUser(userInput)
	if err != nil {
		return userPayloadError("updateUser", err), nil
	}

	user, err := r.assembleUser(*updatedUser)
	if err != nil {
		return userPayloadError("updateUser", err), nil
	}

	return &model.UserPayload{
		User: user,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (*model.DeletePayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return deletePayloadError("deleteUser", errUnauthorized()), nil
	}

	err := r.UserUsecase.DeleteUser(userID)
	if err != nil {
		return deletePayloadError("deleteUser", err), nil
	}

	return &model.DeletePayload{
		Status: true,
	}, nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, input model.FollowUserInput) (*model.UserPayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return userPayloadError("followUser", errUnauthorized()), nil
	}

	if err := r.UserUsecase.FollowUser(userID, input.UserToFollowID); err != nil {
		return userPayloadError("followUser", err), nil
	}

	user, err := r.UserUsecase.GetUserByID(userID)
	if err != nil {
		return userPayloadError("followUser", err), nil
	}

	assembledUser, err := r.assembleUser(*user)
	if err != nil {
		return userPayloadError("followUser", err), nil
	}

	return &model.UserPayload{
		User: assembledUser,
	}, nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, input model.UnfollowUserInput) (*model.UserPayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return userPayloadError("unfollowUser", errUnauthorized()), nil
	}

	if err := r.UserUsecase.UnfollowUser(userID, input.UserToUnfollowID); err != nil {
		return userPayloadError("unfollowUser", err), nil
	}

	user, err := r.UserUsecase.GetUserByID(userID)
	if err != nil {
		return userPayloadError("unfollowUser", err), nil
	}

	assembledUser, err := r.assembleUser(*user)
	if err != nil {
		return userPayloadError("unfollowUser", err), nil
	}

	return &model.UserPayload{
		User: assembledUser,
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.PostPayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return postPayloadError("createPost", errUnauthorized()), nil
	}

	postInput := post.CreatePostInput{
		Description: input.Description,
		AuthorID:    userID,
	}

	createdPost, err := r.PostUsecase.CreatePost(ctx, postInput)
	if err != nil {
		return postPayloadError("createPost", err), nil
	}

	post, err := r.assemblePost(*createdPost)
	if err != nil {
		return postPayloadError("createPost", err), nil
	}

	return &model.PostPayload{
		Post: post,
	}, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*model.PostPayload, error) {
	postInput := post.UpdatePostInput{
		ID:          input.PostID,
		Description: &input.Description,
	}

	updatedPost, err := r.PostUsecase.UpdatePost(postInput)
	if err != nil {
		return postPayloadError("updatePost", err), nil
	}

	post, err := r.assemblePost(*updatedPost)
	if err != nil {
		return postPayloadError("updatePost", err), nil
	}

	return &model.PostPayload{
		Post: post,
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string) (*model.DeletePayload, error) {
	if err := r.PostUsecase.DeletePost(postID); err != nil {
		return deletePayloadError("deletePost", err), nil
	}

	return &model.DeletePayload{
		Status: true,
	}, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.CommentPayload, error) {
	userID, ok := authentication.UserIDFromContext(ctx)
	if !ok {
		return commentPayloadError("createComment", errUnauthorized()), nil
	}

	commentInput := comment.CreateCommentInput{
		AuthorID: userID,
		PostID:   input.PostID,
		Message:  input.Message,
	}

	createdComment, err := r.CommentUsecase.CreateComment(ctx, commentInput)
	if err != nil {
		return commentPayloadError("createComment", err), nil
	}

	comment, err := r.assembleComment(*createdComment)
	if err != nil {
		return commentPayloadError("createComment", err), nil
	}

	return &model.CommentPayload{
		Comment: comment,
	}, nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input model.UpdateCommentInput) (*model.CommentPayload, error) {
	commentInput := comment.UpdateCommentInput{
		ID:      input.CommentID,
		Message: &input.Message,
	}

	updatedComment, err := r.CommentUsecase.UpdateComment(commentInput)
	if err != nil {
		return commentPayloadError("updateComment", err), nil
	}

	comment, err := r.assembleComment(*updatedComment)
	if err != nil {
		return commentPayloadError("updateComment", err), nil
	}

	return &model.CommentPayload{
		Comment: comment,
	}, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string) (*model.DeletePayload, error) {
	if err := r.CommentUsecase.DeleteComment(commentID); err != nil {
		return deletePayloadError("deleteComment", err), nil
	}

	return &model.DeletePayload{
		Status: true,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	user, err := r.UserUsecase.GetUserByID(userID)
	if err != nil {
		return nil, err
	}

	return r.assembleUser(*user)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserUsecase.GetUsers()
	if err != nil {
		return nil, err
	}

	result := make([]*model.User, 0, len(users))
	for _, user := range users {
		assembledUser, err := r.assembleUser(user)
		if err != nil {
			return nil, err
		}

		result = append(result, assembledUser)
	}

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, postID string) (*model.Post, error) {
	post, err := r.PostUsecase.GetPostByID(postID)
	if err != nil {
		return nil, err
	}

	return r.assemblePost(*post)
}

// UserPosts is the resolver for the userPosts field.
func (r *queryResolver) UserPosts(ctx context.Context, userID string) ([]*model.Post, error) {
	posts, err := r.PostUsecase.GetPostsByAuthorID(userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Post, 0, len(posts))
	for _, post := range posts {
		assembledPost, err := r.assemblePost(post)
		if err != nil {
			return nil, err
		}

		result = append(result, assembledPost)
	}

	return result, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, commentID string) (*model.Comment, error) {
	comment, err := r.CommentUsecase.GetCommentByID(commentID)
	if err != nil {
		return nil, err
	}

	return r.assembleComment(*comment)
}

// PostComments is the resolver for the postComments field.
func (r *queryResolver) PostComments(ctx context.Context, postID string) ([]*model.Comment, error) {
	comments, err := r.CommentUsecase.GetCommentsByPostID(postID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Comment, 0, len(comments))
	for _, comment := range comments {
		assembledComment, err := r.assembleComment(comment)
		if err != nil {
			return nil, err
		}

		result = append(result, assembledComment)
	}

	return result, nil
}

// PostCreated is the resolver for the postCreated field.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	posts, err := r.PostUsecase.SubscribeCreatedPost(ctx)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Post)
	go func() {
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case post, ok := <-posts:
				if !ok {
					return
				}

				assembledPost, err := r.assemblePost(*post)
				if err != nil {
					continue
				}

				select {
				case <-ctx.Done():
					return
				case out <- assembledPost:
				}
			}
		}
	}()

	return out, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	comments, err := r.CommentUsecase.SubscribeAddedComment(ctx, postID)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Comment)
	go func() {
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case comment, ok := <-comments:
				if !ok {
					return
				}

				assembledComment, err := r.assembleComment(*comment)
				if err != nil {
					continue
				}

				select {
				case <-ctx.Done():
					return
				case out <- assembledComment:
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
